name: Rustlings progress

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - id: test
        name: Run test script
        run: |
          cd .github/
          result=$(make ci_rustlings_check)
          echo "result=$result" | tee "$GITHUB_OUTPUT"
      - name: Generate custom badge
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: progress
          LABEL: 'Progress'
          ICON: 'rust'
          STATUS: ${{ steps.test.outputs.result }}
          COLOR: blue
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
